### ISSUE TITLE
timeout reading large file

### ISSUE THREAD

**Issue by da-w-xu** [sdball/blammo#1]
hello there!

getting a timeout searching back on a 1.2gb file (my search term is at the start of the file):

works great:
```
dxu@K27K2J-T7Jh blammo % time curl "http://localhost:4000/api/logs?filename=big.log&lines=10&filter=2024" | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2563  100  2563    0     0   308k      0 --:--:-- --:--:-- --:--:--  312k
      10     136    2563
curl "http://localhost:4000/api/logs?filename=big.log&lines=10&filter=2024"  0.00s user 0.01s system 42% cpu 0.028 total
wc  0.00s user 0.00s system 11% cpu 0.027 total

dxu@K27K2J-T7Jh blammo % time curl "http://localhost:4000/api/logs?filename=big.log&lines=1000&filter=2024" | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  159k  100  159k    0     0  16.3M      0 --:--:-- --:--:-- --:--:-- 17.2M
    1000   11307  163130
curl "http://localhost:4000/api/logs?filename=big.log&lines=1000&filter=2024"  0.00s user 0.01s system 37% cpu 0.030 total
wc  0.00s user 0.00s system 12% cpu 0.028 total
```

starts timing out:
```
dxu@K27K2J-T7Jh blammo % time curl "http://localhost:4000/api/logs?filename=big.log&lines=10&filter=2023"
timed out reading logfilecurl "http://localhost:4000/api/logs?filename=big.log&lines=10&filter=2023"  0.01s user 0.01s system 0% cpu 5.034 total
```
seems to time out after 5seconds?

can we add a way to toggle the timeout for searching large files? (via a param, or env var, or just remove it :D)

**Comment by sdball** [comment]
Hello! Thanks for taking a look!

Yes it does indeed timeout after 5 seconds as part of the Task/Supervision setup to avoid one request from taking too many resources. This is likely happening because you're filtering for a pattern that doesn't occur frequently or only occurs near the beginning of the file.

https://github.com/sdball/blammo/blob/main/DESIGN.md#reading-lines-from-the-end-of-a-file

We could certainly disable the timeout or allow it to be configurable: but for that approach to really be viable I'd do better to rewrite the filter-first path to read backwards through the file in chunks vs reading an increasingly large chunk. I'm happy to do that but can you also take a look at the tail-first API? If that meets our needs then it's already ready and should not have any timeout issues.

e.g.

```
curl "http://localhost:4000/api/logs/tail-first?filename=big.log&lines=10&filter=2023"
```

**Comment by sdball** [comment]
@da-w-xu I've gone ahead and increased the timeout for filter-first and rewrote its approach to step back through the file in chunks (as called out in the design file). I've correspondingly updated the design file and the commit for this issue has full details.
